# Generated by Django 3.2.9 on 2021-11-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('period', models.CharField(blank=True, max_length=10)),
                ('range', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('institute', models.CharField(blank=True, max_length=20)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('target_number', models.IntegerField(blank=True)),
                ('office', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'research_information',
            },
        ),
    ]
